version: "3"
services:
  gjg_app:
    container_name: gjg_app
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file: 
      - ".env.example"
    links:
      - redis
      - mongo
  mongo:
    container_name: mongo
    image: "mongo:4.2"
    volumes:
      - ./db:/data/db
    restart: always
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: "redis:alpine"
    volumes:
      - ./data:/data/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"