version: "3"
services:
  gjg_app:
    container_name: gjg_app
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment: 
      - NODE_ENV=development
      - MONGODB_URI_LOCAL=mongodb://mongo:27017/gjg
      - SESSION_SECRET=GJGSECRET
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
      - mongo
  mongo:
    container_name: mongo
    image: "mongo:4.2"
    volumes:
      - ./mongo_data:/data/db
    restart: always
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: "redis:alpine"
    volumes:
      - ./redis_data:/data/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"